# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[constraint]]
  name = "github.com/cosmos/cosmos-sdk"
  revision = "3864d5b1bd9d7081fb5f8bc3f9a014e9a0462756"

[[override]]
  name = "github.com/golang/protobuf"
  version = "=1.1.0"

[[constraint]]
  name = "github.com/go-pg/pg"
  version = "=v7.1.6"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "=v1.3.0"

[[override]]
  name = "github.com/tendermint/iavl"
  version = "=v0.12.0"

[[override]]
  name = "github.com/tendermint/tendermint"
  version = "v0.29.2"

[[override]]
  name = "github.com/tendermint/go-amino"
  version = "v0.14.1"

[[constraint]]
  name = "github.com/samsarahq/thunder"
  version = "=v0.4.0"

[[constraint]]
  name = "github.com/oklog/ulid"
  version = "=v1.3.1"

[[constraint]]
  name = "github.com/dghubble/gologin"
  version = "=v2.1.0"

## deps without releases:

[[override]]
  name = "golang.org/x/crypto"
  source = "https://github.com/tendermint/crypto"
  revision = "3764759f34a542a3aef74d6b02e35be7ab893bba"

[prune]
  go-tests = true
  unused-packages = true
